name: Daily QCB prices

on:
  schedule:
    - cron: "10 16 * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: python -m pip install --upgrade pip requests

      - name: Fetch Quarter Century Bonanza
        run: python scripts/fetch_qcb.py

      - name: Commit & push
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config user.name "price-bot"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          git commit -m "QCB snapshot $(date -u +%F)" || exit 0
          git push https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }} HEAD:${{ github.ref_name }}
